OnlineElearningSystem/Controllers/CategoryController.cs
using OnlineElearningSystem.BL;
using OnlineElearningSystem.DAL;
using OnlineElearningSystem.Entity;
using OnlineElearningSystem.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace OnlineElearningSystem.Controllers
{
    public class CategoryController : Controller
    {
		CourseBL course = new CourseBL();
		CourseRepositry courseRepositry = new CourseRepositry();
		CategoryRepositry categoryRepositry = new CategoryRepositry();
		// GET: Category
		public ActionResult Index()
        {
            return View();
        }
		[HttpGet]
		public ActionResult CreateCategory()
		{
			return View();
		}
		[HttpPost]
		public ActionResult CreateCategory(CategoryModel categoryModel)
		{
			if (ModelState.IsValid)
			{

				var newUser = AutoMapper.Mapper.Map<CategoryModel, Category>(categoryModel);
				course.AddCategory(newUser);
			}
			return View();
		}

		IEnumerable<Category> CategoryList;
		public ActionResult Handle_Category()
		{
			CategoryList = categoryRepositry.ViewCategory();
			return View(CategoryList);
		}

		[HttpGet]
		public ActionResult Edit(Category category)
		{
			Category categoryDetail = categoryRepositry.FetchData(category.categoryId);
			return View(categoryDetail);
		}
		[HttpPost]
		public ActionResult Edit(CategoryModel categoryModel)
		{

			Category category = new Category();
			category.categoryName = categoryModel.categoryName;
			category.categoryId = categoryModel.categoryId;
			categoryRepositry.UpdateCategory(category);
			return RedirectToAction("Handle_Category");
		}

		public ActionResult Delete(int id)
		{
			categoryRepositry.DeleteCategory(id);
			return RedirectToAction("Handle_Category");
		}
	}
}

OnlineElearningSystem/Controllers/CourseController.cs
using OnlineElearningSystem.BL;
using OnlineElearningSystem.DAL;
using OnlineElearningSystem.Entity;
using OnlineElearningSystem.Models;
using System.Collections.Generic;

using System.Web.Mvc;

namespace OnlineElearningSystem.Controllers
{
    public class CourseController : Controller
    {
		CourseBL courseBl = new CourseBL();
		CourseRepositry courseRepositry = new CourseRepositry();
		// GET: Course
		public ActionResult Index()
        {
            return View();
        }

		[HttpGet]
		public ActionResult CreateCourse()
		{
			ViewBag.Category = new SelectList(courseBl.GetCategory(), "categoryId", "categoryName");
			return View();
		}
		[HttpPost]
		public ActionResult CreateCourse(CourseModel courseModel)
		{
			ViewBag.Category = new SelectList(courseBl.GetCategory(), "categoryId", "categoryName");
			if (ModelState.IsValid)
			{

				var newUser = AutoMapper.Mapper.Map<CourseModel, Course>(courseModel);
				CourseBL course = new CourseBL();
				course.AddCourse(newUser);
			}
			return View();
		}
		IEnumerable<Course> CourseList;
		public ActionResult Handle_Course()
		{
			CourseList = courseRepositry.ViewCourse();
			return View(CourseList);
		}

		[HttpGet]
		public ActionResult Edit(Course course)
		{
			ViewBag.Category = new SelectList(courseBl.GetCategory(), "categoryId", "categoryName");
			Course courseDetail = courseRepositry.FetchData(course.courseId);
			return View(courseDetail);
		}
		[HttpPost]
		public ActionResult Edit(CourseModel courseModel)
		{

			Course course = new Course();
			course.courseName = courseModel.courseName;
			course.courseId = courseModel.courseId;
			course.categoryId = courseModel.categoryId;
			courseRepositry.UpdateCourse(course);
			return RedirectToAction("Handle_Course");
		}

		public ActionResult Delete(int id)
		{
			courseRepositry.DeleteCourse(id);
			return RedirectToAction("Handle_Course");
		}

	}
}

OnlineElearningSystem/Controllers/LinkController.cs
using OnlineElearningSystem.BL;
using OnlineElearningSystem.DAL;
using OnlineElearningSystem.Entity;
using OnlineElearningSystem.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace OnlineElearningSystem.Controllers
{
    public class LinkController : Controller
    {
		// GET: Link
		CourseBL course = new CourseBL();
		LinkRepositry linkRepositry = new LinkRepositry();
		public ActionResult Index()
        {
            return View();
        }
		[HttpGet]
		public ActionResult CreateLink()
		{
			ViewBag.Topic = new SelectList(course.GetTopic(), "topicId", "topicName");
			return View();
		}
		[HttpPost]
		public ActionResult CreateLink(LinkModel linkModel)
		{
			ViewBag.Topic = new SelectList(course.GetTopic(), "topicId", "topicName");
			if (ModelState.IsValid)
			{

				var newUser = AutoMapper.Mapper.Map<LinkModel,Link>(linkModel);
				CourseBL course = new CourseBL();
				course.AddLink(newUser);
			}
			return View();
		}
		IEnumerable<Link> LinkList;
		public ActionResult Handle_Link()
		{
			LinkList = linkRepositry.ViewLink();
			return View(LinkList);
		}

		[HttpGet]
		public ActionResult Edit(Link link)
		{
		
			ViewBag.Topic = new SelectList(course.GetTopic(), "topicId", "topicName");
			Link linkDetail = linkRepositry.FetchData(link.linkId);
			return View(linkDetail);
		}
		[HttpPost]
		public ActionResult Edit(LinkModel linkModel)
		{

			Link link = new Link();
			link.link = linkModel.link;
			link.linkId = linkModel.linkId;
			link.topicId = linkModel.topicId;
			linkRepositry.UpdateLink(link);
			return RedirectToAction("Handle_Link");
		}

		public ActionResult Delete(int id)
		{
			linkRepositry.DeleteLink(id);
			return RedirectToAction("Handle_Link");
		}
	}
}

OnlineElearningSystem/Controllers/TopicController.cs
using OnlineElearningSystem.BL;
using OnlineElearningSystem.DAL;
using OnlineElearningSystem.Entity;
using OnlineElearningSystem.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace OnlineElearningSystem.Controllers
{
    public class TopicController : Controller
    {
		CourseBL course = new CourseBL();
		TopicRepositry topicRepositry = new TopicRepositry();
		// GET: Topic
		public ActionResult Index()
        {
            return View();
        }

		[HttpGet]
		public ActionResult Createtopic()
		{
			ViewBag.Course = new SelectList(course.GetCourse(), "courseId", "courseName");
			return View();
		}
		[HttpPost]
		public ActionResult Createtopic(TopicModel topicModel)
		{
			ViewBag.Course = new SelectList(course.GetCourse(), "courseId", "courseName");
			if (ModelState.IsValid)
			{

				var newUser = AutoMapper.Mapper.Map<TopicModel,Topic> (topicModel);
				CourseBL course = new CourseBL();
				course.AddTopic(newUser);
			}
			return View();
		}
		IEnumerable<Topic> TopicList;
		public ActionResult Handle_Topic()
		{
			TopicList = topicRepositry.ViewTopic();
			return View(TopicList);
		}

		[HttpGet]
		public ActionResult Edit(Topic topic)
		{
			ViewBag.Course = new SelectList(course.GetCourse(), "courseId", "courseName");
			Topic topicDetail = topicRepositry.FetchData(topic.topicId);
			return View(topicDetail);
		}
		[HttpPost]
		public ActionResult Edit(TopicModel topicModel)
		{

			Topic topic = new Topic();
			topic.topicName = topicModel.topicName;
			topic.topicId = topicModel.topicId;
			topic.courseId = topicModel.courseId;
			topic.cost = topicModel.cost;
			topicRepositry.UpdateTopic(topic);
			return RedirectToAction("Handle_Topic");
		}

		public ActionResult Delete(int id)
		{
			topicRepositry.DeleteTopic(id);
			return RedirectToAction("Handle_Topic");
		}
	}
}

OnlineElearningSystem/Controllers/UserController.cs
using OnlineElearningSystem.BL;
using OnlineElearningSystem.DAL;
using OnlineElearningSystem.Entity;
using OnlineElearningSystem.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace OnlineElearningSystem.Controllers
{
	[HandleError]	
    public class UserController : Controller
    {
		public static UserDetail role { get; set; }
		public ActionResult Index()
        {
            return View();
        }
		[HttpGet]
		public ActionResult SignUp()
		{
			return View();
		
		}
		[HttpPost]
		[ActionName("SignUp")]
		public ActionResult CreateUser(UserDetailModel userDetailModel)
		{
			
			IEnumerable<UserDetail> detail = UserRepository.SignUp();
			if (ModelState.IsValid)
			{

				var newUser = AutoMapper.Mapper.Map<UserDetailModel, UserDetail>(userDetailModel);
				//UserDetail userDetail = new UserDetail
				//{
				//	userId = userDetailModel.userId,
				//	userName = userDetailModel.userName,
				//	gender = userDetailModel.gender,
				//	confirmPassword = userDetailModel.confirmPassword,
				//	mobileNumber = userDetailModel.mobileNumber,
				//	mailId = userDetailModel.mailId,
				//	dateOfBirth = userDetailModel.dateOfBirth,
				//	mediumOfStudy = userDetailModel.mediumOfStudy,
				//	userRcvcole = "User",
				//};
				User user = new User();
				user.SignUp(newUser);
			}
			return View();
		}
		[HttpGet]
		public ActionResult Login()
		{
			return View();

		}
		[HttpPost]
		[ActionName("Login")]
		public ActionResult Login(LoginModel loginModel)
		{

			if (ModelState.IsValid)
			{
				UserDetail userDetail = new UserDetail
				{
					userName = loginModel.userName,
					confirmPassword = loginModel.password,

				};
				User user = new User();
				role = user.Login(userDetail);
				return RedirectToAction("Home", role);


				//if (user.Login(userDetail) == "Admin")
				//{
				//	return RedirectToAction("Handle_User", "Admin");
				//}
				//else if (user.Login(userDetail) == "User")
				//{
				//	return RedirectToAction("");
				//}
				//else
				//{
				//	ViewBag.Message = "Username or Password incorrect";
				//	return RedirectToAction("SignUp");
				//}
			}
				return View();
		}
		public ActionResult Home()
		{
			return View();
		}
		[CustomError]
		public ActionResult Test()
		{
			throw new Exception("Error have been occured");
		}

	}
}

OnlineElearningSystem/Views/User/Home.cshtml
@{
	ViewBag.Title = "Home";
}

<h2>Welcome to DJPortal</h2>

@using (Html.BeginForm())
{
	@Html.ActionLink("Logout", "Login", "User")<br />
	if (OnlineElearningSystem.Controllers.UserController.role.userRole == "Admin")
	{
		@Html.ActionLink("Handle_User", "Handle_User", "Admin")<br />
		@Html.ActionLink("CreateCategory", "CreateCategory", "Category")<br />
		@Html.ActionLink("CreateCourse", "CreateCourse", "Course")<br />
		@Html.ActionLink("CreateTopic", "CreateTopic", "Topic")<br />
		@Html.ActionLink("CreateLink", "CreateLink", "Link")<br />
		@Html.ActionLink("Handle_Category", "Handle_Category", "Category")<br />
		@Html.ActionLink("Handle_Course", "Handle_Course", "Course")<br />
		@Html.ActionLink("Handle_Topic", "Handle_Topic", "Topic")<br />
		@Html.ActionLink("Handle_Link", "Handle_Link", "Link")<br />
	}
	else if (OnlineElearningSystem.Controllers.UserController.role.userRole == "User")
	{
		@Html.ActionLink("", "", "")
	}
}

OnlineElearningSystem/Views/User/Login.cshtml
@model OnlineElearningSystem.Models.LoginModel

@{
	ViewBag.Title = "Login";
}
@if (ViewBag.Message != null)
{
	Response.Write(ViewBag.Message);
}
<h2>Login</h2>
@using (Html.BeginForm("Login", "User", FormMethod.Post))
{
	<table>

		<tr>
			<td>userName</td>
			<td style="margin-top:100%;height:10%">
				@Html.TextBoxFor(model => model.userName, new { @maxlength = "50" })
				@Html.ValidationMessageFor(model => model.userName, "", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>password</td>
			<td style="margin-top:100%;height:10%">
				@Html.TextBoxFor(model => model.password, new { @maxlength = "30" })
				@Html.ValidationMessageFor(model => model.password, "", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>
				<input type="submit" runat="server" value="Login" />
			</td>
		</tr>
	</table>
}

OnlineElearningSystem/Views/User/SignUp.cshtml
@model OnlineElearningSystem.Models.UserDetailModel

@{
	ViewBag.Title = "SignUp";
}

<h2>SignUp</h2>

@Html.ValidationSummary(true)
@using (Html.BeginForm("SignUp", "User", FormMethod.Post))
{

	<table  class="HeadTags" >
		@{
			Html.RenderPartial("Eportal");
		}
		<tr>
			<td>userName</td>
			<td >
				@Html.TextBoxFor(model => model.userName,new { @maxlength = "50" })
				@Html.ValidationMessageFor(model => model.userName,"",new { style="color:red"} ) 
			</td>
		</tr>
		<tr>
			<td>password</td>
			<td >
				@Html.PasswordFor(model => model.password, new { @maxlength = "30" })
				@Html.ValidationMessageFor(model => model.password,"", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>confirmPassword</td>
			<td >
				@Html.PasswordFor(model => model.confirmPassword, new { @maxlength = "30" })
				@Html.ValidationMessageFor(model => model.confirmPassword, "", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>gender</td>
			<td >
				@Html.RadioButtonFor(m => m.gender, "Male")Male
				@Html.RadioButtonFor(m => m.gender, "Female")Female

			</td>
		</tr>
		<tr>
			<td>mobileNumber</td>
			<td >
				@Html.TextBoxFor(model => model.mobileNumber, new { @maxlength = "10" })
				@Html.ValidationMessageFor(model => model.mobileNumber, "", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>mailId</td>
			<td>
				@Html.TextBoxFor(model => model.mailId, new { @maxlength = "100" })
				@Html.ValidationMessageFor(model => model.mailId, "", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>dateOfBirth</td>
			<td >
				@Html.TextBoxFor(model => model.dateOfBirth, new { @maxlength = "30" })
				@Html.ValidationMessageFor(model => model.dateOfBirth, "", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>mediumOfStudy</td>
			<td >
				@Html.TextBoxFor(model => model.mediumOfStudy, new { @maxlength = "15" })
				@Html.ValidationMessageFor(model => model.mediumOfStudy, "", new { style = "color:red" })
			</td>
		</tr>
		<tr>
			<td>
				<input type="submit" value="Submit" />
				@Html.Partial("ElearnView")

			</td>
		</tr>
	</table>
}